# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            RoboComp
tagline:          ''
description:      'A simple robotics framework.'
url:              http://rajathkumarmp.github.io
baseurl:          /rcwebsite2

author:
  name:           'RoboComp'
  url:            github.com/robocomp

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/robocomp
